### PR TITLE
Display searched skills

### PR DESCRIPTION
**Pull request by heron2014**
Related [issue 210](https://github.com/FAC-GM/app/issues/210)

@nelsonic please have a look at this PR, thanks.

### CODE REVIEW

**Comment by iteles** [comment]
**Before we merge this in**, can we do a little more for the UI please?

I've added some suggestions [in the issue](https://github.com/FAC-GM/app/issues/210#issuecomment-176376248) - I hope they're helpful!

**Comment by heron2014** [comment]
@iteles no worries, just updated :)

**Comment by nelsonic** [comment]
@iteles the colorscheme matches brand guidelines. can I merge?

**Comment by iteles** [comment]
@nelsonic Yes!

**Pull request merged**
