### PR TITLE
add link to profile

### PR DESCRIPTION
**Pull request by SimonLab**
see [issue 232](https://github.com/FAC-GM/app/issues/232)

@nelsonic please feel free to review the code when you have some time. Thanks

### CODE REVIEW

**Comment by nelsonic** [comment]
@SimonLab this looks good and the regression test is simple/effective. nice one. :+1:

**Comment by nelsonic** [comment]
@SimonLab does the app re-deploy to heroku automatically based on update to the `master` branch...?

**Comment by SimonLab** [comment]
@nelsonic yes the heroku deploy is linked to master branch on Github

**Comment by nelsonic** [comment]
I thought so... :thought_balloon: 
But it was taking a few minutes so curious.
Looks like the issue #232 is *fixed*. :+1:

**Pull request merged**
