### PR TITLE
Update client

### PR DESCRIPTION
**Pull request by heron2014**
Related to #462 

### This PR has to be merged after [460](https://github.com/FAC-GM/app/pull/460)

@nelsonic can you have a look at this PR?thank you.

### CODE REVIEW

**Comment by nelsonic** [comment]
@heron2014 I will review this evening. currently stuck trying to fix something ...

**Comment by nelsonic** [comment]
@heron2014 please merge master into this branch so there are fewer commits (_less code to review in the PR_) _thanks_!

**Comment by heron2014** [comment]
@nelsonic merged :+1:

**Comment by nelsonic** [comment]
looks good. 👍

**Pull request merged**
