### PR TITLE
Remove checkbox when email sent within last 30 days

### PR DESCRIPTION
**Pull request by heron2014**
## after discussing with Ines, this feature can be added to this sprint

Related to [issue 401](https://github.com/FAC-GM/app/issues/401)

@nelsonic if you have a moment, have a look at this PR, thank you

### CODE REVIEW

**Comment by iteles** [comment]
@heron2014 Just had word from Nick that this is not in this sprint. Let's chat about this tomorrow.

**Comment by nelsonic** [comment]
@heron2014 assign when ready. (*after you've discussed with Nick*) :+1:

**Comment by heron2014** [comment]
@nelsonic whenever you free please have a look at this PR, thank you

**Comment by nelsonic** [comment]
@heron2014 looks good. merged.

**Pull request merged**
