### PR TITLE
add limit for memory use

### PR DESCRIPTION
**Pull request by SimonLab**
see #455

@nelsonic do you mind to check the package.json change? thanks

### CODE REVIEW

**Comment by nelsonic** [comment]
Looks good. as discussed. Will merge once Travis confirms build passes. 👍

**Comment by nelsonic** [comment]
@SimonLab Memory usage status? ❓

**Comment by SimonLab** [comment]
@nelsonic At the moment everything is fine but I still think that we might need to try to reduce the memory usage of the application, it still seems quiet high:

memoryusage

**Comment by nelsonic** [comment]
It's capped at the level you set. so its *all good*. Node will automatically use all available memory and perform Garbage Collection when it's running out. Safe to move on. 👍

**Pull request merged**
