### PR TITLE
Match score with pie chart

### PR DESCRIPTION
**Pull request by heron2014**
# Ready to merge
Related to [issue 206](https://github.com/FAC-GM/app/issues/206)

@nelsonic  can you please check this PR?

### CODE REVIEW

**Comment by iteles** [comment]
I think we need to put a little more work into the UI element here - it's not immediately clear at a glance. Worth putting 20 minutes into sketching 3 or 4 different options on paper so we can compare a few different approaches?

**Comment by nelsonic** [comment]
Agree that we need to start approaching Adam's design as much/soon as possible... :lipstick:

**Comment by SimonLab** [comment]
Some Ideas:
- Have a white background for the pie and maybe just a blue colour for the percentage
- Just have a text instead of the pie chart on the top right
- Display the pie chart and the number under the pie

**Comment by nelsonic** [comment]
@SimonLab good suggestions. :+1: 
Do we have the diagram/wireframe made by Adam?

**Comment by heron2014** [comment]
Wireframe by Adam: 
wireframe

Just to clarify : should we start changing the whole design into this one? or only pie chart?

**Comment by SimonLab** [comment]
Also it looks like Adam's pie chart is filling counter clockwise rotation. Do we want to keep this direction?

**Comment by nelsonic** [comment]
@heron2014 thanks for uploading the image. it does not appear to be included in the description of the story: #206 

good question regarding the design! we need to move towards using *their* colorscheme as soon as possible.
But given that there are quite a few changes to be made, its worth creating a *specific* **UI** in the *Backlog* and giving it a time estimate. 

@SimonLab well *spotted*. having the pie-chart complete counter-clockwise is unusual, but there *might* be a *reason* why @Adam-JF has done it that way, worth checking. 

In the *first* instance if we can just use their colorscheme for this feature and see what it looks like that would be a step in the right direction. I know we all like the Yellow/Blue theme, however they have invested in their branding and need the app to look as much like the website as possible...

**Comment by heron2014** [comment]
There is a slight margin on {M} which can be correct once we apply flex box layout. For testing match-score this PR is ready. 
@nelsonic have a look please.

**Comment by nelsonic** [comment]
@heron2014 lets *ship* it the way it is. 
if Adam wants you to spend a bit more time on the Style we can allocate the time at the *start* of *next sprint*. see discussion in: https://github.com/FAC-GM/app/issues/226#issuecomment-175633860

**Comment by heron2014** [comment]
@nelsonic totally agree!

**Pull request merged**
