### PR TITLE
Activity viewed by

### PR DESCRIPTION
**Pull request by heron2014**
# Please let us know when this PR has been reviewed (the extension need to be published first)
Related to [issue 382](https://github.com/FAC-GM/app/issues/382)

# Ready for review
### Please add new env var - which we placed in the Google Drive (two include FIXTURES)

More information in regards the code is in [here](https://github.com/FAC-GM/app/issues/382#issuecomment-206948653)

By running npm test, we now get the necessary values from the database and all the data needed for the test should be on the localhost

@nelsonic please have a look at this code, thank you

### CODE REVIEW

**Comment by heron2014** [comment]
sorry @nelsonic for such an ugly notification from coverage!

**Comment by nelsonic** [comment]
@heron2014 coverage *cannot* decrease.

**Comment by nelsonic** [comment]
Steps to test:
+ [ ] create new test file: `test/viewed_by.test.js`
+ [ ] create fixture that does *not* have a `viewedBy` key (*to follow the conditional assignment branch on [line 73](https://codecov.io/github/FAC-GM/app/lib/api.js?ref=bdcfcfca5d5590b680d8cc57e8a4fc732b28a41a#l-73) 
+ [ ] write test that accesses the `/profile` endpoint and views the candidate who does *not* have a `viewedBy` entry

**Comment by heron2014** [comment]
I was confused which fixture file should I use to test these condition. Creating a new file is the best option. Thanks @nelsonic

**Comment by nelsonic** [comment]
@heron2014 when I tried this last night I just added:
```js
  { "url": "https://www.linkedin.com/in/noviewedby",
    "connections": 123,
    "connectedTo": [],
    "notes":[{"createdAt":"02.02.2016", "author": "Simon", "id": 12, "notes":"", "status": "phone-screen", "company": "FAC"}],
     "fullname": "No viewedBy",
     "headline": "Not Interesting Enough",
     "location": "Argentina",
     "favourite": [],
     "jobApplications": [{"jobID": "1", "timestamp": 1458213700542, "comments": "some comment", "skillset": "Css"}],
     "current": "",
     "picture":"https://static.licdn.com/scds/common/u/images/themes/katy/ghosts/person/ghost_person_150x150_v1.png",
     "contacts": {
         "email": "",
         "phone":"",
         "im": [],
         "address": "Argentina" },
    "summary": "",
    "skills":[],
    "languages":[],
    "experience":{
        "current": [],
        "past":[]}},
```
to the `test/fixtures/fixture-js.json` file. (*below "Nick"*).
You want the fixture to be *inserted* when you are testing i.e. when `npm run resetdb` gets executed.

**Comment by heron2014** [comment]
@iteles I posted a comment in the activity issue in regards your question [comment](https://github.com/FAC-GM/app/issues/382#issuecomment-207802297).

**Comment by nelsonic** [comment]
Code looks good. merging. :+1:

**Pull request merged**
