### PR TITLE
Email feature

### PR DESCRIPTION
**Pull request by heron2014**
Basic solution for sending email at the moment (no tests)
Related to [issue 211](https://github.com/FAC-GM/app/issues/211) & [issue 212](https://github.com/FAC-GM/app/issues/212) & [issue 243](https://github.com/FAC-GM/app/issues/243)

@nelsonic please have a look at this PR, thank you

### CODE REVIEW

**Comment by nelsonic** [comment]
@heron2014 I understand that testing email is not "*easy*" but we can't merge a PR that has a failing test... https://travis-ci.org/FAC-GM/app/builds/108601817
@SimonLab do you have time to help debug the 3 failing tests?

**Comment by heron2014** [comment]
@nelsonic yes, we are trying to fix that 3 failing tests. I was advised to make a PR for you to only check the orogress (not to merged until the tests are done).

**Comment by nelsonic** [comment]
@heron2014 the code looks good. 
I would split out `lib/email.js` into smaller (*more testable*) components...
But its fine for now if you include some sort of test. even for a failure condition. 
It will not give you 100% coverage *today*, but I can help you pay that *tech debt* at the *start* of the next sprint. 
I had to be *creative* with how I tested my code to get to 100% ... https://travis-ci.org/nelsonic/sendemail-gmail/builds/107907762 its a *two* step process which I can show you on a Hangout if you have time...

**Comment by heron2014** [comment]
@nelsonic that would be great, anytime you free.

**Comment by nelsonic** [comment]
@heron2014 please let me know when you want me to review this. we should merge it in soon to test...

**Comment by SimonLab** [comment]
@nelsonic yes you can review this PR and merge it if you are happy with it. Thanks

**Comment by SimonLab** [comment]
Just a note, to test this PR, the users need to reconnect to the app to be able to use the new api scope

**Comment by nelsonic** [comment]
Code looks good. I am merging this branch on the understanding that additional tests and simplification will be added as required/per our discussion. :+1:

**Comment by SimonLab** [comment]
:+1:

**Comment by heron2014** [comment]
thanks @nelsonic . Additional tests will be added.

**Pull request merged**
