### PR TITLE
update the user with idGoogle on first connection, 

### PR DESCRIPTION
**Pull request by SimonLab**
see #481

If a user connects for the first time into the application we need to define her property idGoogle. This property is used for the dashboard and to define the statuses of candidates.

@nelsonic can you check this PR, thanks :mag:

### CODE REVIEW

**Comment by nelsonic** [comment]
@SimonLab please re-assign to me when Travis is happy. 👍

**Comment by nelsonic** [comment]
@SimonLab [`stream-to-promise`](https://www.npmjs.com/package/stream-to-promise) ... 
I don't understand why it's needed...?
https://github.com/FAC-GM/app/blob/c4231e00c3e6271ed4240e2d48320908e51d23fe/test/upload_cv.test.js

**Comment by SimonLab** [comment]
@nelsonic we use stream to promise to create a multipart/form-data payload to be send our cv test. It allows us to build easily the header of the request.

**Comment by SimonLab** [comment]
@nelsonic the tests are fixed! Instead of using the package stream-to-promise I just built the payload manually.

**Pull request merged**
