### PR TITLE
highlighter fixed on summary and spaces fixed

### PR DESCRIPTION
**Pull request by heron2014**
Related to: 
[issue 114](https://github.com/FAC-GM/app/issues/114)
[issue 116](https://github.com/FAC-GM/app/issues/116)

@iteles can you please check this PR?

### CODE REVIEW

**Comment by iteles** [comment]
Looks great, thanks!

Could you also create a regression test for this case?

**Comment by SimonLab** [comment]
Ok. I'm adding some tests now.

**Comment by SimonLab** [comment]
@nelsonic I add some regression tests for this feature.

**Comment by iteles** [comment]
@simonLab Any idea why travis isn't happy?

**Comment by SimonLab** [comment]
@iteles it should pass now. Just an css index selector problem as I has an element in the html strucure

**Comment by nelsonic** [comment]
Looks good. :+1:

**Comment by iteles** [comment]
👍🏻

**Pull request merged**
