### PR TITLE
update npm packages dependencies

### PR DESCRIPTION
**Pull request by SimonLab**
# Not ready yet
#409

@nelsonic do you mind?

### CODE REVIEW

**Comment by SimonLab** [comment]
It seems that codecov wake up! So please don't merge yet and we will add some tests to have 100% coverage

**Comment by iteles** [comment]
Do you guys not have an app version number in your `package.json`?

Looks like there's a code coverage issue before @nelsonic can review.

**Comment by SimonLab** [comment]
@iteles there is a version number (even if we haven't udpated for a while). But I think the problem is that codecov report that we don't have 100% coverage and it fail the test. Do you think the version of the app can be another problem?

**Comment by iteles** [comment]
@SimonLab The version of the app won't cause a problem, I just noticed that it wasn't part of your updated lines and it should be, but this is partly my bad because I haven't made the time to write release notes for every release.

On the coverage, it's not because it's not 100% it's because merging this branch into master will _decrease_ coverage (from 98.7% to 98.63%). Worth investigating as I'm sure @nelsonic will bring it up.

**Comment by SimonLab** [comment]
:+1: thanks, I updated the version of codecov it might have change the covereage percentage, we investigate...

**Comment by SimonLab** [comment]
I'm closing this PR. The dependencies will be updated with the PR based on the branch https://github.com/FAC-GM/app/tree/clean-email-handler

**Pull request closed without merging**
