### PR TITLE
Updates hapi.js dependency

### PR DESCRIPTION
**Pull request by iteles**
Updates hapiJS dependency as the `insecure` dependency doesn't look that great on the readme!

gm-dependencies-insecure

### CODE REVIEW

**Comment by iteles** [comment]
Uh-oh. Have to investigate code coverage. Will have to do it early tomorrow when I have more time!

**Comment by nelsonic** [comment]
Ouch... 
Do we not have a *test* for the `pageNum < page_url_next` `else` condition...?
https://codecov.io/github/FAC-GM/app/lib/home.js?ref=a06994da1de0f772110170e91ef1a1f4614f7f6c#l-92

**Comment by SimonLab** [comment]
I thought we have! I will have a look tonight or tomorrow.

**Comment by nelsonic** [comment]
Cool. thanks for investigating it. :+1:

**Comment by iteles** [comment]
https://codecov.io/github/FAC-GM/app/lib/home.js?ref=a06994da1de0f772110170e91ef1a1f4614f7f6c#l-92

**Comment by SimonLab** [comment]
Ready to merge! I just reload the test on travis.

**Pull request merged**
