### PR TITLE
info section for the candidate 

### PR DESCRIPTION
**Pull request by heron2014**
Related to #420 

This PR is only related to the first part of this feature  - saving/updating the candidate expectations/info. 

The basic UI is in [here](https://github.com/FAC-GM/app/issues/420#issuecomment-216528332)
General overview is [here](https://github.com/FAC-GM/app/issues/420#issuecomment-216530539)

@nelsonic please have a look when you have a moment, thank you.

### CODE REVIEW

**Comment by iteles** [comment]
@nelsonic - Please hold off just a moment.

@heron2014 Doesn't the user functionality need to be merged in tomorrow first?
But equally importantly, don't we need to deploy status and notes at the same time to prevent loss of functionality?

**Comment by heron2014** [comment]
@iteles as discussed in Gitter, this PR is not linked to users. This part only have addition information to the candidate. We still have status on Notes.

**Comment by SimonLab** [comment]
This PR just add 4 fields to the existing candidate object: 
- salary expected
- salary current
- notice period
- location

these fields are all string field. This feature is not linked to the status or the notes, so a user still need to add a note to define the status of a candidate

**Comment by nelsonic** [comment]
@heron2014 code looks good. please resolve merge conflicts and ping me when ready. 👍

**Comment by heron2014** [comment]
@nelsonic ready to be merge. Tested by product owner - [here](https://github.com/FAC-GM/app/issues/420#issuecomment-217435136), thank you!

**Comment by nelsonic** [comment]
Nice one. merging. 👍

**Pull request merged**
