### PR TITLE
update environment variable and normalize url

### PR DESCRIPTION
**Pull request by SimonLab**
linked to thoses issues [157](https://github.com/FAC-GM/app/issues/157), [156](https://github.com/FAC-GM/app/issues/156), [121](https://github.com/FAC-GM/app/issues/121).

@nelsonic do you want to have a look at the code?

### CODE REVIEW

**Comment by nelsonic** [comment]
@SimonLab are you fixing the build before I review?

**Comment by SimonLab** [comment]
@nelsonic yes It should be good very soon!

**Comment by nelsonic** [comment]
Looks good. :+1: 
Let me know when I can merge. thanks.

**Comment by SimonLab** [comment]
now it's good!

**Comment by nelsonic** [comment]
merged. :+1:

**Pull request merged**
