### PR TITLE
Csv v5

### PR DESCRIPTION
**Pull request by SimonLab**
# Ready to review

see #510 
@nelsonic please have a look at this one, thank you

This PR allow a user to search by skills on a list of candidates

### CODE REVIEW

**Comment by nelsonic** [comment]
@heron2014 please merge master into this branch, resolve conflicts then assign to me for review. 👍 
(_hope you are well_. 😉  )

**Comment by heron2014** [comment]
@nelsonic this branch is now merge with master, I am good - thanks for asking :smile:

**Comment by heron2014** [comment]
@nelsonic this feature hasn't been yet tested by the PO in the staging area. This will be done tomorrow morning.

**Comment by nelsonic** [comment]
Please assign back to me when its been tested by PO. 😉

**Comment by heron2014** [comment]
@nelsonic this PR is still waiting for approval for the last modification. See [comment](https://github.com/FAC-GM/app/issues/510#issuecomment-229619032).

**Comment by heron2014** [comment]
@nelsonic this PR has been [approved](https://github.com/FAC-GM/app/issues/510#issuecomment-229653174) although on the staging area is deployed also the next PR which is csv-v6 which is the decode/encode url on listName. So if we merge this one , would be great to merge straight after the csv-v6 as well. Let me know what you think :)

**Comment by nelsonic** [comment]
@heron2014 I will review both this evening. 👍

**Comment by nelsonic** [comment]
Code looks good. (_if I was being picky I would ask you to `lint` it..._)
merging. 👍

**Pull request merged**
