### PR TITLE
Csv v3

### PR DESCRIPTION
**Pull request by heron2014**
## Ready to merge after scv-v2 is merged

Related to #505 

[Basic UI](https://github.com/FAC-GM/app/issues/505#issuecomment-228042163) 

@nelsonic do you mind to have a look at this PR, thanks

### CODE REVIEW

**Comment by nelsonic** [comment]
@heron2014  / @SimonLab please merge master in to this branch to reduce the number of changes then ping me so I know to review/merge. thanks. 👍

**Comment by SimonLab** [comment]
@nelsonic the master branch is merged with this branch now :+1:

**Comment by nelsonic** [comment]
👀

**Comment by nelsonic** [comment]
Looks good. 👍

**Pull request merged**
